<?php

namespace Database\Seeders;

use App\Models\Beneficiary;
use App\Models\Community;
use App\Models\ExtensionProgram;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class BeneficiarySeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get existing communities and programs
        $communities = Community::all();
        $programs = ExtensionProgram::all();
        $director = User::where('role', 'director')->first();

        if ($communities->isEmpty() || $programs->isEmpty()) {
            $this->command->warn('Communities or Programs not found. Please run ExtensionProgramSeeder first.');
            return;
        }

        $creatorId = $director?->id ?? 1;
        
        // Sample data for diverse beneficiaries
        $beneficiaryData = [
            // Group 1: College Student Tutors from Tara, Basa Program (NCR-based)
            [
                'first_name' => 'Maria',
                'middle_name' => 'Reyes',
                'last_name' => 'Santos',
                'date_of_birth' => Carbon::create(2002, 3, 15),
                'age' => 22,
                'gender' => 'female',
                'email' => 'maria.santos@student.lnu.edu.ph',
                'phone' => '09161234567',
                'address' => '123 Mahogany St.',
                'barangay' => 'San Juan',
                'municipality' => 'Quezon City',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'College Student Tutor',
                'monthly_income' => 15000.00,
                'occupation' => 'Student',
                'educational_attainment' => 'College',
                'marital_status' => 'Single',
                'number_of_dependents' => 2,
                'status' => 'active',
                'notes' => 'Chemistry major, participates in Tara, Basa tutoring program. Excellent academic performance.',
            ],
            [
                'first_name' => 'Juan',
                'middle_name' => 'Cruz',
                'last_name' => 'Dela Cruz',
                'date_of_birth' => Carbon::create(2001, 7, 22),
                'age' => 23,
                'gender' => 'male',
                'email' => 'juan.delacruz@student.lnu.edu.ph',
                'phone' => '09171234568',
                'address' => '456 Narra Ave.',
                'barangay' => 'Diliman',
                'municipality' => 'Quezon City',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'College Student Tutor',
                'monthly_income' => 16500.00,
                'occupation' => 'Student',
                'educational_attainment' => 'College',
                'marital_status' => 'Single',
                'number_of_dependents' => 3,
                'status' => 'active',
                'notes' => 'Education major, leading reading intervention sessions for Grade 1 learners.',
            ],
            [
                'first_name' => 'Ana',
                'middle_name' => 'Gutierrez',
                'last_name' => 'Rodriguez',
                'date_of_birth' => Carbon::create(2002, 11, 8),
                'age' => 21,
                'gender' => 'female',
                'email' => 'ana.rodriguez@student.lnu.edu.ph',
                'phone' => '09181234569',
                'address' => '789 Pines St.',
                'barangay' => 'Tondo',
                'municipality' => 'Manila',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'College Student Tutor',
                'monthly_income' => 15000.00,
                'occupation' => 'Student',
                'educational_attainment' => 'College',
                'marital_status' => 'Single',
                'number_of_dependents' => 1,
                'status' => 'active',
                'notes' => 'English Education student. Conducting tutoring sessions in 2 schools.',
            ],
            [
                'first_name' => 'Carlos',
                'middle_name' => 'Mercado',
                'last_name' => 'Hernandez',
                'date_of_birth' => Carbon::create(2001, 5, 30),
                'age' => 24,
                'gender' => 'male',
                'email' => 'carlos.hernandez@student.lnu.edu.ph',
                'phone' => '09191234570',
                'address' => '321 Acacia Ln.',
                'barangay' => 'Ermita',
                'municipality' => 'Manila',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'College Student Tutor',
                'monthly_income' => 17000.00,
                'occupation' => 'Student',
                'educational_attainment' => 'College',
                'marital_status' => 'Single',
                'number_of_dependents' => 4,
                'status' => 'active',
                'notes' => 'Math Education major, top performer in tutoring quality assessments.',
            ],
            [
                'first_name' => 'Rosa',
                'middle_name' => 'Manuel',
                'last_name' => 'Garcia',
                'date_of_birth' => Carbon::create(2003, 2, 14),
                'age' => 21,
                'gender' => 'female',
                'email' => 'rosa.garcia@student.lnu.edu.ph',
                'phone' => '09201234571',
                'address' => '654 Daisy Dr.',
                'barangay' => 'San Juan',
                'municipality' => 'Quezon City',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'College Student Tutor',
                'monthly_income' => 15000.00,
                'occupation' => 'Student',
                'educational_attainment' => 'College',
                'marital_status' => 'Single',
                'number_of_dependents' => 2,
                'status' => 'inactive',
                'notes' => 'Transferred to another program. Completed 18 tutoring sessions.',
            ],

            // Group 2: Youth Development Workers
            [
                'first_name' => 'Miguel',
                'middle_name' => 'Santos',
                'last_name' => 'Vergara',
                'date_of_birth' => Carbon::create(1995, 8, 10),
                'age' => 30,
                'gender' => 'male',
                'email' => 'miguel.vergara@lnu.edu.ph',
                'phone' => '09211234572',
                'address' => '987 Orchid St.',
                'barangay' => 'Diliman',
                'municipality' => 'Quezon City',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'Youth Development Worker',
                'monthly_income' => 18500.00,
                'occupation' => 'Youth Coordinator',
                'educational_attainment' => 'College',
                'marital_status' => 'Married',
                'number_of_dependents' => 3,
                'status' => 'active',
                'notes' => 'Coordinates community engagement in Tara, Basa program. 5 years community development experience.',
            ],
            [
                'first_name' => 'Lucia',
                'middle_name' => 'Aquino',
                'last_name' => 'Morales',
                'date_of_birth' => Carbon::create(1998, 6, 25),
                'age' => 27,
                'gender' => 'female',
                'email' => 'lucia.morales@lnu.edu.ph',
                'phone' => '09221234573',
                'address' => '147 Sampaguita Ave.',
                'barangay' => 'Tondo',
                'municipality' => 'Manila',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'Youth Development Worker',
                'monthly_income' => 17000.00,
                'occupation' => 'Program Officer',
                'educational_attainment' => 'College',
                'marital_status' => 'Single',
                'number_of_dependents' => 1,
                'status' => 'active',
                'notes' => 'Manages parent engagement sessions and facilitates "Nanay-Tatay" programs.',
            ],
            [
                'first_name' => 'Pedro',
                'middle_name' => 'Reyes',
                'last_name' => 'Fernandez',
                'date_of_birth' => Carbon::create(1997, 4, 12),
                'age' => 28,
                'gender' => 'male',
                'email' => 'pedro.fernandez@lnu.edu.ph',
                'phone' => '09231234574',
                'address' => '258 Rose Rd.',
                'barangay' => 'Ermita',
                'municipality' => 'Manila',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'Youth Development Worker',
                'monthly_income' => 18000.00,
                'occupation' => 'Community Facilitator',
                'educational_attainment' => 'College',
                'marital_status' => 'Married',
                'number_of_dependents' => 2,
                'status' => 'active',
                'notes' => 'Oversees implementation compliance and quality assurance across 3 schools.',
            ],

            // Group 3: Beneficiaries from Leyte Region (Palo area) - possibly for other programs
            [
                'first_name' => 'Delia',
                'middle_name' => 'Villanueva',
                'last_name' => 'Martinez',
                'date_of_birth' => Carbon::create(2000, 9, 18),
                'age' => 25,
                'gender' => 'female',
                'email' => 'delia.martinez@student.lnu.edu.ph',
                'phone' => '09241234575',
                'address' => '369 Narra St.',
                'barangay' => 'Palo National High School Area',
                'municipality' => 'Palo',
                'province' => 'Leyte',
                'beneficiary_category' => 'Student Beneficiary',
                'monthly_income' => 5000.00,
                'occupation' => 'Student',
                'educational_attainment' => 'High School',
                'marital_status' => 'Single',
                'number_of_dependents' => 0,
                'status' => 'active',
                'notes' => 'Grade 2 learner receiving intensive reading support through Tara, Basa program.',
            ],
            [
                'first_name' => 'Javier',
                'middle_name' => 'Lintag',
                'last_name' => 'Canutos',
                'date_of_birth' => Carbon::create(2000, 12, 5),
                'age' => 25,
                'gender' => 'male',
                'email' => 'javier.canutos@student.lnu.edu.ph',
                'phone' => '09251234576',
                'address' => '471 Yakal Ave.',
                'barangay' => 'Cogon Elementary School Area',
                'municipality' => 'Cogon',
                'province' => 'Leyte',
                'beneficiary_category' => 'Student Beneficiary',
                'monthly_income' => 4500.00,
                'occupation' => 'Student',
                'educational_attainment' => 'Elementary',
                'marital_status' => 'Single',
                'number_of_dependents' => 0,
                'status' => 'active',
                'notes' => 'Grade 1 learner making progress in reading proficiency. Active in parent engagement sessions.',
            ],
            [
                'first_name' => 'Elena',
                'middle_name' => 'Ortiz',
                'last_name' => 'Santiago',
                'date_of_birth' => Carbon::create(1992, 7, 22),
                'age' => 33,
                'gender' => 'female',
                'email' => 'elena.santiago@email.com',
                'phone' => '09261234577',
                'address' => '582 Mahogany Ln.',
                'barangay' => 'Barangay Maharlika',
                'municipality' => 'Palo',
                'province' => 'Leyte',
                'beneficiary_category' => 'Parent Participant',
                'monthly_income' => 12000.00,
                'occupation' => 'Vendor',
                'educational_attainment' => 'High School',
                'marital_status' => 'Married',
                'number_of_dependents' => 3,
                'status' => 'active',
                'notes' => 'Active participant in Nanay-Tatay sessions. Mother of 2 students in program.',
            ],
            [
                'first_name' => 'Francisco',
                'middle_name' => 'Buot',
                'last_name' => 'Oredeza',
                'date_of_birth' => Carbon::create(1988, 3, 30),
                'age' => 37,
                'gender' => 'male',
                'email' => 'francisco.oredeza@email.com',
                'phone' => '09271234578',
                'address' => '693 Pines Dr.',
                'barangay' => 'Barangay San Ricardo',
                'municipality' => 'Palo',
                'province' => 'Leyte',
                'beneficiary_category' => 'Community Leader',
                'monthly_income' => 20000.00,
                'occupation' => 'Barangay Kagawad',
                'educational_attainment' => 'High School',
                'marital_status' => 'Married',
                'number_of_dependents' => 4,
                'status' => 'active',
                'notes' => 'Barangay official supporting program implementation and community mobilization.',
            ],
            [
                'first_name' => 'Violeta',
                'middle_name' => 'Oclarit',
                'last_name' => 'Albano',
                'date_of_birth' => Carbon::create(1995, 11, 8),
                'age' => 30,
                'gender' => 'female',
                'email' => 'violeta.albano@lnu.edu.ph',
                'phone' => '09281234579',
                'address' => '804 Acacia St.',
                'barangay' => 'Palo National High School Area',
                'municipality' => 'Palo',
                'province' => 'Leyte',
                'beneficiary_category' => 'Faculty Coordinator',
                'monthly_income' => 35000.00,
                'occupation' => 'School Administrator',
                'educational_attainment' => 'Graduate',
                'marital_status' => 'Married',
                'number_of_dependents' => 2,
                'status' => 'active',
                'notes' => 'Palo NHS administrator coordinating school partnership with Tara, Basa program.',
            ],

            // Group 4: Additional diverse beneficiaries
            [
                'first_name' => 'Angelito',
                'middle_name' => 'Gapuz',
                'last_name' => 'Reyes',
                'date_of_birth' => Carbon::create(1994, 5, 14),
                'age' => 31,
                'gender' => 'male',
                'email' => 'angelito.reyes@email.com',
                'phone' => '09291234580',
                'address' => '915 Orchid Rd.',
                'barangay' => 'San Juan',
                'municipality' => 'Quezon City',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'Community Beneficiary',
                'monthly_income' => 18000.00,
                'occupation' => 'Mechanic',
                'educational_attainment' => 'High School',
                'marital_status' => 'Married',
                'number_of_dependents' => 3,
                'status' => 'active',
                'notes' => 'Maintains community learning center where tutoring sessions are conducted.',
            ],
            [
                'first_name' => 'Corazon',
                'middle_name' => 'Laguna',
                'last_name' => 'Valdez',
                'date_of_birth' => Carbon::create(1993, 8, 20),
                'age' => 32,
                'gender' => 'female',
                'email' => 'corazon.valdez@email.com',
                'phone' => '09301234581',
                'address' => '326 Sampaguita Ln.',
                'barangay' => 'Diliman',
                'municipality' => 'Quezon City',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'Community Beneficiary',
                'monthly_income' => 16500.00,
                'occupation' => 'Seamstress',
                'educational_attainment' => 'High School',
                'marital_status' => 'Single',
                'number_of_dependents' => 2,
                'status' => 'active',
                'notes' => 'Provides meals for tutors during Tara, Basa sessions. Single mother of 2 learners.',
            ],
            [
                'first_name' => 'Ricardo',
                'middle_name' => 'Manlangit',
                'last_name' => 'Pascual',
                'date_of_birth' => Carbon::create(1996, 2, 11),
                'age' => 29,
                'gender' => 'male',
                'email' => 'ricardo.pascual@lnu.edu.ph',
                'phone' => '09311234582',
                'address' => '437 Daisy Ave.',
                'barangay' => 'Tondo',
                'municipality' => 'Manila',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'Program Assistant',
                'monthly_income' => 16000.00,
                'occupation' => 'Administrative Assistant',
                'educational_attainment' => 'College',
                'marital_status' => 'Single',
                'number_of_dependents' => 1,
                'status' => 'active',
                'notes' => 'Handles documentation and data management for Tara, Basa program.',
            ],
            [
                'first_name' => 'Soledad',
                'middle_name' => 'Ongcoy',
                'last_name' => 'Dalumpines',
                'date_of_birth' => Carbon::create(1991, 10, 27),
                'age' => 34,
                'gender' => 'female',
                'email' => 'soledad.dalumpines@email.com',
                'phone' => '09321234583',
                'address' => '548 Rose St.',
                'barangay' => 'Ermita',
                'municipality' => 'Manila',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'Community Beneficiary',
                'monthly_income' => 14000.00,
                'occupation' => 'Housekeeper',
                'educational_attainment' => 'Elementary',
                'marital_status' => 'Married',
                'number_of_dependents' => 4,
                'status' => 'inactive',
                'notes' => 'Previous participant. Transferred to province due to family relocation.',
            ],
            [
                'first_name' => 'Alfred',
                'middle_name' => 'Villanueva',
                'last_name' => 'Bautista',
                'date_of_birth' => Carbon::create(1999, 4, 6),
                'age' => 26,
                'gender' => 'male',
                'email' => 'alfred.bautista@student.lnu.edu.ph',
                'phone' => '09331234584',
                'address' => '659 Narra St.',
                'barangay' => 'San Juan',
                'municipality' => 'Quezon City',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'College Student Tutor',
                'monthly_income' => 15500.00,
                'occupation' => 'Student',
                'educational_attainment' => 'College',
                'marital_status' => 'Single',
                'number_of_dependents' => 2,
                'status' => 'active',
                'notes' => 'Physics Education major. Conducts tutoring in low-income schools.',
            ],
            [
                'first_name' => 'Victoria',
                'middle_name' => 'Gutierrez',
                'last_name' => 'Calleja',
                'date_of_birth' => Carbon::create(2001, 6, 19),
                'age' => 24,
                'gender' => 'female',
                'email' => 'victoria.calleja@student.lnu.edu.ph',
                'phone' => '09341234585',
                'address' => '770 Yakal Ln.',
                'barangay' => 'Diliman',
                'municipality' => 'Quezon City',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'College Student Tutor',
                'monthly_income' => 15000.00,
                'occupation' => 'Student',
                'educational_attainment' => 'College',
                'marital_status' => 'Single',
                'number_of_dependents' => 1,
                'status' => 'active',
                'notes' => 'Liberal Arts major with focus on reading and language development.',
            ],
            [
                'first_name' => 'Roberto',
                'middle_name' => 'Malunes',
                'last_name' => 'Gonzales',
                'date_of_birth' => Carbon::create(1996, 9, 14),
                'age' => 29,
                'gender' => 'male',
                'email' => 'roberto.gonzales@lnu.edu.ph',
                'phone' => '09351234586',
                'address' => '881 Pines Ave.',
                'barangay' => 'Tondo',
                'municipality' => 'Manila',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'Youth Development Worker',
                'monthly_income' => 17500.00,
                'occupation' => 'Training Officer',
                'educational_attainment' => 'College',
                'marital_status' => 'Married',
                'number_of_dependents' => 2,
                'status' => 'active',
                'notes' => 'Conducts training for college tutors and monitors implementation quality.',
            ],
            [
                'first_name' => 'Rosario',
                'middle_name' => 'Pagatpat',
                'last_name' => 'Labao',
                'date_of_birth' => Carbon::create(1992, 1, 8),
                'age' => 34,
                'gender' => 'female',
                'email' => 'rosario.labao@email.com',
                'phone' => '09361234587',
                'address' => '992 Sampaguita Dr.',
                'barangay' => 'Ermita',
                'municipality' => 'Manila',
                'province' => 'National Capital Region',
                'beneficiary_category' => 'Parent Participant',
                'monthly_income' => 11000.00,
                'occupation' => 'Laundry Worker',
                'educational_attainment' => 'High School',
                'marital_status' => 'Married',
                'number_of_dependents' => 3,
                'status' => 'active',
                'notes' => 'Consistent attendance in Nanay-Tatay parent sessions. Advocating for reading at home.',
            ],
        ];

        // Create beneficiaries and assign random programs
        foreach ($beneficiaryData as $data) {
            // Find community by name
            $community = $communities->firstWhere('name', function ($name) use ($data) {
                return str_contains($data['barangay'], $name) || str_contains($data['municipality'], $name);
            });

            // If community not found by direct match, get first community (fallback)
            if (!$community) {
                $community = $communities->first();
            }

            $data['community_id'] = $community->id;
            $data['created_by'] = $creatorId;
            $data['updated_by'] = $creatorId;

            // Randomly assign 1-2 programs to this beneficiary
            $assignedPrograms = $programs->random(rand(1, 2))->pluck('id')->toArray();
            $data['program_ids'] = json_encode($assignedPrograms);

            // Create the beneficiary
            Beneficiary::updateOrCreate(
                [
                    'first_name' => $data['first_name'],
                    'last_name' => $data['last_name'],
                    'date_of_birth' => $data['date_of_birth'],
                ],
                $data
            );
        }

        $this->command->info('BeneficiarySeeder completed successfully! Created ' . count($beneficiaryData) . ' beneficiary records.');
    }
}
