<?php

namespace Database\Seeders;

use App\Models\NeedsAssessment;
use App\Models\Community;
use App\Models\User;
use Illuminate\Database\Seeder;

class NeedsAssessmentSeeder extends Seeder
{
    /**
     * Run the database seeds with comprehensive sample assessments.
     */
    public function run(): void
    {
        $secretary = User::where('role', 'secretary')->first();
        $communities = Community::take(3)->get();

        if ($communities->count() < 1) {
            return; // Skip if no communities
        }

        $assessments = [
            [
                'community_id' => $communities[0]->id ?? 1,
                'quarter' => 'Q1',
                'year' => 2024,
                'respondent_first_name' => 'Maria',
                'respondent_middle_name' => 'Cruz',
                'respondent_last_name' => 'Santos',
                'respondent_age' => 45,
                'respondent_civil_status' => 'Married',
                'respondent_sex' => 'Female',
                'respondent_religion' => 'Catholic',
                'respondent_educational_attainment' => json_encode(['High School']),
                'family_composition' => json_encode(['5 members: 2 adults, 3 children']),
                'barangay_educational_facilities' => json_encode(['Elementary Primary', 'Secondary']),
                'livelihood_options' => json_encode(['Farming', 'Raising animals']),
                'interested_in_livelihood_training' => 'Yes',
                'areas_of_educational_interest' => json_encode(['Math', 'English']),
                'preferred_training_time' => 'Morning 8-12',
                'preferred_training_days' => json_encode(['Wednesday', 'Saturday']),
                'desired_training' => json_encode(['Vegetable Farming', 'Animal Husbandry']),
                'common_illnesses' => json_encode(['Colds', 'Headache']),
                'action_when_sick' => json_encode(['Hospital/Health Center', 'Herbal Medicine']),
                'barangay_medical_supplies_available' => json_encode(['Health Center', 'Ambulance']),
                'has_barangay_health_programs' => 'Yes',
                'benefits_from_barangay_programs' => 'Yes',
                'programs_benefited_from' => json_encode(['Free Vaccine', 'Free Consultation']),
                'water_source' => json_encode(['NAWASA', 'Deep Well']),
                'water_source_distance' => 'Just outside',
                'garbage_disposal_method' => json_encode(['Compost pit']),
                'household_member_currently_studying' => 'No',
                'interested_in_continuing_studies' => 'No',
                'has_own_toilet' => 'Yes',
                'toilet_type' => json_encode(['Flush toilet']),
                'keeps_animals' => 'Yes',
                'animals_kept' => json_encode(['Chicken', 'Duck']),
                'house_type' => json_encode(['Half concrete/wood']),
                'tenure_status' => json_encode(['Own house/land']),
                'has_electricity' => 'Yes',
                'light_source_without_power' => json_encode(['Solar lamp']),
                'appliances_owned' => json_encode(['TV', 'Refrigerator', 'Electric Fan']),
                'barangay_recreational_facilities' => json_encode(['Basketball Court', 'Volleyball Court']),
                'use_of_free_time' => json_encode(['Playing basketball', 'Watching TV']),
                'member_of_organization' => 'Yes',
                'organization_types' => json_encode(['Civic', 'Religious']),
                'organization_meeting_frequency' => 'Monthly',
                'organization_usual_activities' => 'Community cleanup, religious gatherings',
                'household_members_in_organization' => json_encode(['Self', 'Spouse']),
                'position_in_organization' => 'Treasurer',
                'family_problems' => json_encode(['Low income']),
                'health_problems' => json_encode(['Malnourished']),
                'educational_problems' => json_encode(['Far school']),
                'employment_problems' => json_encode(['Lack of employment']),
                'infrastructure_problems' => json_encode(['Difficult roads']),
                'economic_problems' => json_encode(['Lack of buyers', 'No capital']),
                'security_problems' => json_encode(['No police assigned']),
                'barangay_service_ratings' => json_encode(['Law Enforcement' => 3, 'Fire Protection' => 2, 'Health Service' => 4, 'Education Service' => 3]),
                'general_feedback' => 'Community needs livelihood training and infrastructure development.',
                'available_for_training' => 'Yes',
                'uploaded_by' => $secretary?->id ?? 1,
            ],
            [
                'community_id' => $communities[0]->id ?? 1,
                'quarter' => 'Q2',
                'year' => 2024,
                'respondent_first_name' => 'Juan',
                'respondent_middle_name' => 'Reyes',
                'respondent_last_name' => 'Dela Cruz',
                'respondent_age' => 38,
                'respondent_civil_status' => 'Single',
                'respondent_sex' => 'Male',
                'respondent_religion' => 'Catholic',
                'respondent_educational_attainment' => json_encode(['College']),
                'family_composition' => json_encode(['3 members: 1 adult, 2 siblings']),
                'barangay_educational_facilities' => json_encode(['Secondary', 'College']),
                'livelihood_options' => json_encode(['Service Work', 'Driving']),
                'interested_in_livelihood_training' => 'Yes',
                'areas_of_educational_interest' => json_encode(['Technology', 'Management']),
                'preferred_training_time' => 'Afternoon 1:30-5',
                'preferred_training_days' => json_encode(['Saturday', 'Sunday']),
                'desired_training' => json_encode(['Computer', 'Electronics']),
                'common_illnesses' => json_encode(['Stress', 'Hypertension']),
                'action_when_sick' => json_encode(['Hospital/Health Center']),
                'barangay_medical_supplies_available' => json_encode(['Health Center', 'Medical Equipment']),
                'has_barangay_health_programs' => 'Yes',
                'benefits_from_barangay_programs' => 'No',
                'programs_benefited_from' => json_encode([]),
                'water_source' => json_encode(['NAWASA']),
                'water_source_distance' => 'Just outside',
                'garbage_disposal_method' => json_encode(['Anywhere']),
                'household_member_currently_studying' => 'No',
                'interested_in_continuing_studies' => 'Yes',
                'has_own_toilet' => 'Yes',
                'toilet_type' => json_encode(['Flush toilet']),
                'keeps_animals' => 'No',
                'animals_kept' => json_encode([]),
                'house_type' => json_encode(['All concrete']),
                'tenure_status' => json_encode(['Own house/land']),
                'has_electricity' => 'Yes',
                'light_source_without_power' => json_encode([]),
                'appliances_owned' => json_encode(['TV', 'Computer', 'Washing Machine', 'Electric Fan']),
                'barangay_recreational_facilities' => json_encode(['Basketball Court']),
                'use_of_free_time' => json_encode(['Playing basketball', 'Chatting']),
                'member_of_organization' => 'Yes',
                'organization_types' => json_encode(['Sports/Recreational']),
                'organization_meeting_frequency' => 'Weekly',
                'organization_usual_activities' => 'Basketball games, sports events',
                'household_members_in_organization' => json_encode(['Self']),
                'position_in_organization' => 'Member',
                'family_problems' => json_encode([]),
                'health_problems' => json_encode(['Stress']),
                'educational_problems' => json_encode([]),
                'employment_problems' => json_encode(['Low income']),
                'infrastructure_problems' => json_encode([]),
                'economic_problems' => json_encode([]),
                'security_problems' => json_encode([]),
                'barangay_service_ratings' => json_encode(['Law Enforcement' => 4, 'Fire Protection' => 4, 'Health Service' => 5]),
                'general_feedback' => 'Seeking career advancement and professional development opportunities.',
                'available_for_training' => 'Yes',
                'uploaded_by' => $secretary?->id ?? 1,
            ],
            [
                'community_id' => $communities[1]->id ?? 1,
                'quarter' => 'Q3',
                'year' => 2024,
                'respondent_first_name' => 'Rosa',
                'respondent_middle_name' => null,
                'respondent_last_name' => 'Reyes',
                'respondent_age' => 62,
                'respondent_civil_status' => 'Widowed',
                'respondent_sex' => 'Female',
                'respondent_religion' => 'Catholic',
                'respondent_educational_attainment' => json_encode(['Elementary']),
                'family_composition' => json_encode(['4 members: grandmother, 2 children, 1 grandchild']),
                'barangay_educational_facilities' => json_encode(['Elementary Primary']),
                'livelihood_options' => json_encode(['Selling', '4Ps']),
                'interested_in_livelihood_training' => 'Yes',
                'areas_of_educational_interest' => json_encode(['Health', 'Laws']),
                'preferred_training_time' => 'Morning 8-12',
                'preferred_training_days' => json_encode(['Wednesday']),
                'desired_training' => json_encode(['Food Processing', 'Handicrafts']),
                'common_illnesses' => json_encode(['Hypertension', 'Diabetes', 'Arthritis']),
                'action_when_sick' => json_encode(['Herbal Medicine', 'Hilot']),
                'barangay_medical_supplies_available' => json_encode(['Health Center']),
                'has_barangay_health_programs' => 'Yes',
                'benefits_from_barangay_programs' => 'Yes',
                'programs_benefited_from' => json_encode(['Free Medicine', 'Free Consultation']),
                'water_source' => json_encode(['River/Stream', 'Spring Water']),
                'water_source_distance' => '250 meters away',
                'garbage_disposal_method' => json_encode(['Anywhere', 'Vacant lot']),
                'household_member_currently_studying' => 'No',
                'interested_in_continuing_studies' => 'No',
                'has_own_toilet' => 'No',
                'toilet_type' => json_encode(['Antipolo style']),
                'keeps_animals' => 'Yes',
                'animals_kept' => json_encode(['Chicken', 'Cat']),
                'house_type' => json_encode(['Nipa/Bamboo']),
                'tenure_status' => json_encode(['Own house/land']),
                'has_electricity' => 'No',
                'light_source_without_power' => json_encode(['Oil lamp', 'Candle']),
                'appliances_owned' => json_encode(['Radio']),
                'barangay_recreational_facilities' => json_encode(['Soccer Field']),
                'use_of_free_time' => json_encode(['Sleeping', 'Staying home']),
                'member_of_organization' => 'No',
                'organization_types' => json_encode([]),
                'organization_meeting_frequency' => null,
                'organization_usual_activities' => null,
                'household_members_in_organization' => json_encode([]),
                'position_in_organization' => null,
                'family_problems' => json_encode(['Cannot support family needs']),
                'health_problems' => json_encode(['Malnourished', 'Sickly children']),
                'educational_problems' => json_encode(['Lack of equipment']),
                'employment_problems' => json_encode(['Lack of employment']),
                'infrastructure_problems' => json_encode(['Difficult roads', 'No electric posts']),
                'economic_problems' => json_encode(['Lack of buyers', 'No capital']),
                'security_problems' => json_encode(['No police assigned', 'Theft']),
                'barangay_service_ratings' => json_encode(['Law Enforcement' => 1, 'Health Service' => 3, 'Infrastructure Service' => 1]),
                'general_feedback' => 'Priority: basic utilities and livelihood for immediate sustenance.',
                'available_for_training' => 'No',
                'reason_not_available' => 'Health concerns and household responsibilities.',
                'uploaded_by' => $secretary?->id ?? 1,
            ],
            [
                'community_id' => $communities[1]->id ?? 1,
                'quarter' => 'Q4',
                'year' => 2024,
                'respondent_first_name' => 'Antonio',
                'respondent_middle_name' => 'Lopez',
                'respondent_last_name' => 'Gonzales',
                'respondent_age' => 45,
                'respondent_civil_status' => 'Married',
                'respondent_sex' => 'Male',
                'respondent_religion' => 'Catholic',
                'respondent_educational_attainment' => json_encode(['High School']),
                'family_composition' => json_encode(['7 members: 2 adults, 4 children, 1 elderly']),
                'barangay_educational_facilities' => json_encode(['Elementary Primary', 'Elementary Intermediate', 'Secondary']),
                'livelihood_options' => json_encode(['Farming', 'Rentals']),
                'interested_in_livelihood_training' => 'Yes',
                'areas_of_educational_interest' => json_encode(['Agricultural Issues']),
                'preferred_training_time' => 'Morning 8-12',
                'preferred_training_days' => json_encode(['Wednesday', 'Saturday']),
                'desired_training' => json_encode(['Food Processing', 'Dress Making']),
                'common_illnesses' => json_encode(['Colds', 'Pneumonia']),
                'action_when_sick' => json_encode(['Hospital/Health Center']),
                'barangay_medical_supplies_available' => json_encode(['Health Center', 'Ambulance']),
                'has_barangay_health_programs' => 'Yes',
                'benefits_from_barangay_programs' => 'Yes',
                'programs_benefited_from' => json_encode(['Free Consultation', 'Free Vaccine']),
                'water_source' => json_encode(['Deep Well', 'Spring Water']),
                'water_source_distance' => 'Just outside',
                'garbage_disposal_method' => json_encode(['Compost pit', 'Vacant lot']),
                'household_member_currently_studying' => 'Yes',
                'interested_in_continuing_studies' => 'Yes',
                'has_own_toilet' => 'Yes',
                'toilet_type' => json_encode(['Water sealed']),
                'keeps_animals' => 'Yes',
                'animals_kept' => json_encode(['Chicken', 'Duck', 'Pig']),
                'house_type' => json_encode(['Half concrete/wood', 'Wood/Bamboo']),
                'tenure_status' => json_encode(['Own house/land']),
                'has_electricity' => 'Yes',
                'light_source_without_power' => json_encode(['Solar lamp']),
                'appliances_owned' => json_encode(['TV', 'Refrigerator', 'Gas Range', 'Electric Fan']),
                'barangay_recreational_facilities' => json_encode(['Basketball Court', 'Volleyball Court', 'Soccer Field']),
                'use_of_free_time' => json_encode(['Playing basketball', 'Working in farm']),
                'member_of_organization' => 'Yes',
                'organization_types' => json_encode(['Civic', 'Agricultural']),
                'organization_meeting_frequency' => 'Monthly',
                'organization_usual_activities' => 'Farm cooperative meetings, crop planning',
                'household_members_in_organization' => json_encode(['Self', 'Spouse']),
                'position_in_organization' => 'Secretary',
                'family_problems' => json_encode(['Low income']),
                'health_problems' => json_encode(['Malnourished']),
                'educational_problems' => json_encode(['Far school']),
                'employment_problems' => json_encode(['Lack of skills']),
                'infrastructure_problems' => json_encode(['Difficult roads', 'No irrigation']),
                'economic_problems' => json_encode(['Low crop yield', 'Market access']),
                'security_problems' => json_encode([]),
                'barangay_service_ratings' => json_encode(['Law Enforcement' => 3, 'Health Service' => 4, 'Infrastructure Service' => 2]),
                'general_feedback' => 'Community needs agricultural training and farm-to-market support.',
                'available_for_training' => 'Yes',
                'uploaded_by' => $secretary?->id ?? 1,
            ],
            [
                'community_id' => $communities[2]->id ?? 1,
                'quarter' => 'Q1',
                'year' => 2025,
                'respondent_first_name' => 'Lucia',
                'respondent_middle_name' => 'Marie',
                'respondent_last_name' => 'Fernandez',
                'respondent_age' => 32,
                'respondent_civil_status' => 'Single',
                'respondent_sex' => 'Female',
                'respondent_religion' => 'Catholic',
                'respondent_educational_attainment' => json_encode(['College']),
                'family_composition' => json_encode(['4 members: 1 adult, 2 siblings, 1 parent']),
                'barangay_educational_facilities' => json_encode(['Secondary', 'College']),
                'livelihood_options' => json_encode(['Service Work', 'Remittance']),
                'interested_in_livelihood_training' => 'No',
                'areas_of_educational_interest' => json_encode([]),
                'preferred_training_time' => null,
                'preferred_training_days' => json_encode([]),
                'desired_training' => json_encode([]),
                'common_illnesses' => json_encode([]),
                'action_when_sick' => json_encode(['Hospital/Health Center']),
                'barangay_medical_supplies_available' => json_encode(['Health Center']),
                'has_barangay_health_programs' => 'Yes',
                'benefits_from_barangay_programs' => 'No',
                'programs_benefited_from' => json_encode([]),
                'water_source' => json_encode(['NAWASA']),
                'water_source_distance' => 'Just outside',
                'garbage_disposal_method' => json_encode(['Community pickup']),
                'household_member_currently_studying' => 'No',
                'interested_in_continuing_studies' => 'No',
                'has_own_toilet' => 'Yes',
                'toilet_type' => json_encode(['Flush toilet']),
                'keeps_animals' => 'No',
                'animals_kept' => json_encode([]),
                'house_type' => json_encode(['All concrete']),
                'tenure_status' => json_encode(['Own house/land']),
                'has_electricity' => 'Yes',
                'light_source_without_power' => json_encode([]),
                'appliances_owned' => json_encode(['TV', 'Computer', 'Washing Machine', 'Refrigerator', 'Electric Fan', 'Karaoke']),
                'barangay_recreational_facilities' => json_encode(['Basketball Court', 'Volleyball Court']),
                'use_of_free_time' => json_encode(['Watching TV', 'Chatting']),
                'member_of_organization' => 'Yes',
                'organization_types' => json_encode(['Civic']),
                'organization_meeting_frequency' => 'Monthly',
                'organization_usual_activities' => 'Community welfare, charity works',
                'household_members_in_organization' => json_encode(['Self']),
                'position_in_organization' => 'Vice President',
                'family_problems' => json_encode([]),
                'health_problems' => json_encode([]),
                'educational_problems' => json_encode([]),
                'employment_problems' => json_encode([]),
                'infrastructure_problems' => json_encode([]),
                'economic_problems' => json_encode([]),
                'security_problems' => json_encode([]),
                'barangay_service_ratings' => json_encode(['Law Enforcement' => 4, 'Fire Protection' => 4, 'Health Service' => 5, 'Education Service' => 5, 'Infrastructure Service' => 4]),
                'general_feedback' => 'Community doing well. Ready to support community development initiatives.',
                'available_for_training' => 'No',
                'uploaded_by' => $secretary?->id ?? 1,
            ],
        ];

        foreach ($assessments as $assessment) {
            NeedsAssessment::create($assessment);
        }
    }
}
